DIR_FILT = filt/
SOURCES_FILT += filt/f_5th.c
OBJECTS_FILT += $(SOURCES_FILT:.c=.o)
LDFLAGS += 


OBJECTS_DIR_FILT += $(subst $(DIR_FILT),$(BUILD_DIR)$(DIR_FILT),$(OBJECTS_FILT))

OBJECTS += $(OBJECTS_FILT)
OBJECTS_FINAL += $(OBJECTS_DIR_FILT)