DIR_MOD = mod/
SOURCES_MOD += mod/mod_fm.c
OBJECTS_MOD += $(SOURCES_MOD:.c=.o)
LDFLAGS += 


OBJECTS_DIR_MOD += $(subst $(DIR_MOD),$(BUILD_DIR)$(DIR_MOD),$(OBJECTS_MOD))

OBJECTS += $(OBJECTS_MOD)
OBJECTS_FINAL += $(OBJECTS_DIR_MOD)